### ISSUE TITLE
Can't see bootstrap styles

### ISSUE THREAD

**Issue by humbertqz** [neckerson/slate-bootstrap#6]
Hi @neckerson  thank you so much for making this. 

I am having a problem trying to see the boostrap styles. I've downloaded the theme with no issues and run **yarn start** again with no warnings, but the preview page does not load the bootstrap css. 

Is there an additional command needed to run the sass compiler?

![yarn_start__open__and_New_Issue_·_neckerson_slate-bootstrap_a-theme-2](https://user-images.githubusercontent.com/875269/68250335-50858780-ffe6-11e9-98bb-fa3ef308eaba.jpg)

![Screen Shot 2019-11-05 at 4 02 05 PM](https://user-images.githubusercontent.com/875269/68250390-71e67380-ffe6-11e9-86d0-8f36302736e0.png)

![Screen Shot 2019-11-05 at 4 02 13 PM](https://user-images.githubusercontent.com/875269/68250395-7579fa80-ffe6-11e9-84dd-3aad9e6d5b83.png)

![Screen Shot 2019-11-05 at 4 08 47 PM](https://user-images.githubusercontent.com/875269/68250467-993d4080-ffe6-11e9-8251-df37d418c338.png)

Again thanks for your help.

**Comment by humbertqz** [comment]
It was not about the css, it was some browser-sync reltated issue, this helped me https://github.com/Shopify/slate/issues/1055#issuecomment-529637521

Thanks again.

**Comment by neckerson** [comment]
Hello @humbertqz! It sounds like you fixed this issue. I'm going to go ahead and upgrade this repo to slate-tools beta19 — this fixes the browser-sync problem referenced in this comment. However, CSS not loading in the theme might point to you not having generated a local SSL certificate. Make sure you have the ssl-check script set up, and run it before `yarn start`.
